const icons = {
  tile: 'fa fa-address-book',
  calendar: 'fa fa-thermometer-empty',
  clock: 'fa fa-power-off',
  car: 'fa fa-wheelchair-alt',
  airplane: 'fa fa-exclamation-triangle',
  bill: 'fa fa-caret-square-o-right',
  menu: 'fa fa-bars',
  delete: 'fa fa-trash',
  filter: 'fa fa-filter',
  lock: 'fa fa-lock',
  user: 'fa fa-user',
  close: 'fa fa-times',
  warning: 'fa fa-exclamation-triangle',
  info: 'fa fa-info-circle',
  error: 'fa fa-times-circle',
  success: 'fa fa-check',
  twitter: 'fa fa-twitter',
  gitLab: 'fa fa-gitlab',
  ellipsisV: 'fa fa-ellipsis-v',
  fb: 'fa fa-facebook-official',
  whatsApp: 'fa fa-whatsapp',
  mail: 'fa fa-envelope-o',
};
export default icons;
